/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9e41e8aa54e67183e4351497f5cec023)
interface __BaseEnv_Env {
	CONTENT_ARTIFACTS: R2Bucket;
	CMS_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
