/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 17fde37c5ae27ae46fd531f7b43e98f6)
interface __BaseEnv_Env {
	CONTENT_ARTIFACTS: R2Bucket;
	MEDIA_DERIVATIVES: R2Bucket;
	CMS_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
