/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9c914108aa69d517db483d92faea08b7)
interface __BaseEnv_Env {
	CMS_DB: D1Database;
	ADMIN_HOST: "localhost";
	ACCESS_TEAM_DOMAIN: "";
	ACCESS_AUD: "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_HOST" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD">> {}
}
