/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5a454b077ae8dc8cdad62946cf58fa72)
interface __BaseEnv_Env {
	CONTENT_ARTIFACTS: R2Bucket;
	MEDIA_ORIGINALS: R2Bucket;
	MEDIA_DERIVATIVES: R2Bucket;
	CMS_DB: D1Database;
	IMAGES: ImagesBinding;
	ADMIN_HOST: "localhost";
	ACCESS_TEAM_DOMAIN: "";
	ACCESS_AUD: "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_HOST" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD">> {}
}
