/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 703147f0ae01be02714ddc15e231f1e8)
interface __BaseEnv_Env {
	ADMIN_HOST: "localhost";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_HOST">> {}
}
